name: Discord Push Notification

on:
  push:
    branches:
      - '**'

jobs:
  discord-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read JSON data
        id: fetch_data
        run: |
          # Parse ip.json values using jq
          VERSION=$(jq -r '.version' ip.json)
          DOWNLOAD=$(jq -r '.push' ip.json)
          CHANGELOGS=$(jq -r '.changelogs' ip.json)

          # Save outputs for subsequent steps
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "download=$DOWNLOAD" >> $GITHUB_OUTPUT
          echo "changelogs=$CHANGELOGS" >> $GITHUB_OUTPUT

      - name: Send Rich Discord Embed
        uses: tsickert/discord-webhook-embed@v2.1.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}

          title: "Launcher got a new update!"

          description: |
            **Repository:** [${{ github.repository }}](https://github.com/${{ github.repository }})
            **Branch:** `${{ github.ref_name }}`
            **Author:** ${{ github.actor }}

            **Version:** `${{ steps.fetch_data.outputs.version }}`

            **Download:**
            [Download Launcher](${{ steps.fetch_data.outputs.download }})

            **Changelogs:**
            > ${{ steps.fetch_data.outputs.changelogs }}

            **Latest Commit Message:**
            > ${{ github.event.head_commit.message }}

          color: 65280
          url: "${{ github.event.head_commit.url }}"
          timestamp: true
